databases:
  - name: rx-cw-postgres
    databaseName: chatwoot
    user: chatwoot
    plan: free
    postgresMajorVersion: 16

services:
  - name: rx-cw-web
    type: web
    runtime: docker
    plan: free
    repo: https://github.com/shadi-crypto/rx-chatwoot.git
    branch: main
    dockerfilePath: ./docker/Dockerfile
    healthCheckPath: /
    envVars:
      - key: RAILS_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: SECRET_KEY_BASE
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: rx-cw-postgres
          property: connectionString
      - key: REDIS_URL
        sync: false
      - key: FRONTEND_URL
        sync: false

  - name: rx-cw-worker
    type: worker
    runtime: docker
    plan: free
    repo: https://github.com/shadi-crypto/rx-chatwoot.git
    branch: main
    dockerfilePath: ./docker/Dockerfile
    envVars:
      - key: RAILS_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: SECRET_KEY_BASE
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: rx-cw-postgres
          property: connectionString
      - key: REDIS_URL
        sync: false
